[2022-09-23T20:46:12.773+0000] {processor.py:156} INFO - Started process (PID=8256) to work on /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:46:12.774+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data_remote.py for tasks to queue
[2022-09-23T20:46:12.775+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:46:12.775+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:46:14.373+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:46:14.297+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data_remote.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_remote.py", line 21, in <module>
    engine = create_engine('postgresql://${{ PGUSER }}:${{ PGPASSWORD }}@${{ PGHOST }}:${{ PGPORT }}/${{ PGDATABASE }}')
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 530, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 715, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 771, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: '${{ PGPORT }}'
[2022-09-23T20:46:14.375+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:46:14.460+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data_remote.py took 1.693 seconds
[2022-09-23T20:46:44.940+0000] {processor.py:156} INFO - Started process (PID=8278) to work on /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:46:44.941+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data_remote.py for tasks to queue
[2022-09-23T20:46:44.942+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:46:44.942+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:46:45.860+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:46:45.464+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data_remote.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_remote.py", line 21, in <module>
    engine = create_engine('postgresql://${{ PGUSER }}:${{ PGPASSWORD }}@${{ PGHOST }}:${{ PGPORT }}/${{ PGDATABASE }}')
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 530, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 715, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 771, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: '${{ PGPORT }}'
[2022-09-23T20:46:45.861+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:46:45.936+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data_remote.py took 0.999 seconds
[2022-09-23T20:47:16.184+0000] {processor.py:156} INFO - Started process (PID=8308) to work on /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:47:16.185+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data_remote.py for tasks to queue
[2022-09-23T20:47:16.186+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:47:16.186+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:47:17.030+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:47:17.025+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data_remote.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_remote.py", line 21, in <module>
    engine = create_engine('postgresql://${{ PGUSER }}:${{ PGPASSWORD }}@${{ PGHOST }}:${{ PGPORT }}/${{ PGDATABASE }}')
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 530, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 715, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 771, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: '${{ PGPORT }}'
[2022-09-23T20:47:17.031+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:47:17.098+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data_remote.py took 0.921 seconds
[2022-09-23T20:47:47.277+0000] {processor.py:156} INFO - Started process (PID=8330) to work on /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:47:47.294+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data_remote.py for tasks to queue
[2022-09-23T20:47:47.296+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:47:47.296+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:47:47.804+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:47:47.801+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data_remote.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_remote.py", line 21, in <module>
    engine = create_engine('postgresql://${{ PGUSER }}:${{ PGPASSWORD }}@${{ PGHOST }}:${{ PGPORT }}/${{ PGDATABASE }}')
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 530, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 715, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 771, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: '${{ PGPORT }}'
[2022-09-23T20:47:47.805+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:47:47.873+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data_remote.py took 0.601 seconds
[2022-09-23T20:48:18.082+0000] {processor.py:156} INFO - Started process (PID=8352) to work on /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:48:18.097+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data_remote.py for tasks to queue
[2022-09-23T20:48:18.098+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:48:18.098+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:48:19.100+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:48:19.071+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data_remote.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_remote.py", line 21, in <module>
    engine = create_engine('postgresql://${{ PGUSER }}:${{ PGPASSWORD }}@${{ PGHOST }}:${{ PGPORT }}/${{ PGDATABASE }}')
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 530, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 715, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 771, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: '${{ PGPORT }}'
[2022-09-23T20:48:19.101+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:48:19.275+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data_remote.py took 1.196 seconds
[2022-09-23T20:48:49.542+0000] {processor.py:156} INFO - Started process (PID=8383) to work on /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:48:49.586+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data_remote.py for tasks to queue
[2022-09-23T20:48:49.587+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:48:49.587+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:48:50.483+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:48:50.480+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data_remote.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data_remote.py", line 21, in <module>
    engine = create_engine('postgresql://${{ PGUSER }}:${{ PGPASSWORD }}@${{ PGHOST }}:${{ PGPORT }}/${{ PGDATABASE }}')
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 530, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 715, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 771, in _parse_rfc1738_args
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: '${{ PGPORT }}'
[2022-09-23T20:48:50.484+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:48:50.543+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data_remote.py took 1.006 seconds
[2022-09-23T20:49:17.119+0000] {processor.py:156} INFO - Started process (PID=8404) to work on /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:49:17.135+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data_remote.py for tasks to queue
[2022-09-23T20:49:17.137+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:49:17.137+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:49:17.947+0000] {processor.py:768} INFO - DAG(s) dict_keys(['loading_data_remote']) retrieved from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:49:22.004+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:49:22.003+0000] {manager.py:508} INFO - Created Permission View: can read on DAG:loading_data_remote
[2022-09-23T20:49:22.100+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:49:22.099+0000] {manager.py:508} INFO - Created Permission View: can delete on DAG:loading_data_remote
[2022-09-23T20:49:22.166+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:49:22.166+0000] {manager.py:508} INFO - Created Permission View: can edit on DAG:loading_data_remote
[2022-09-23T20:49:22.169+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:49:22.168+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-09-23T20:49:22.240+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:49:22.239+0000] {dag.py:2594} INFO - Creating ORM DAG for loading_data_remote
[2022-09-23T20:49:22.305+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:49:22.304+0000] {dag.py:3328} INFO - Setting next_dagrun for loading_data_remote to 2022-01-01T00:00:00+00:00, run_after=2022-01-01T00:00:00+00:00
[2022-09-23T20:49:22.455+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data_remote.py took 5.347 seconds
[2022-09-23T20:49:52.703+0000] {processor.py:156} INFO - Started process (PID=8425) to work on /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:49:52.706+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data_remote.py for tasks to queue
[2022-09-23T20:49:52.708+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:49:52.707+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:49:54.680+0000] {processor.py:768} INFO - DAG(s) dict_keys(['loading_data_remote']) retrieved from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:49:55.217+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:49:55.216+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-09-23T20:49:55.313+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:49:55.313+0000] {dag.py:3328} INFO - Setting next_dagrun for loading_data_remote to None, run_after=None
[2022-09-23T20:49:55.530+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data_remote.py took 2.832 seconds
[2022-09-23T20:50:25.882+0000] {processor.py:156} INFO - Started process (PID=8447) to work on /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:50:25.901+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data_remote.py for tasks to queue
[2022-09-23T20:50:25.939+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:50:25.937+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:50:37.019+0000] {processor.py:768} INFO - DAG(s) dict_keys(['loading_data_remote']) retrieved from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:51:02.174+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:51:01.953+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-09-23T20:51:13.909+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:51:13.909+0000] {dag.py:3328} INFO - Setting next_dagrun for loading_data_remote to None, run_after=None
[2022-09-23T20:51:14.136+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data_remote.py took 48.259 seconds
[2022-09-23T20:51:45.114+0000] {processor.py:156} INFO - Started process (PID=8477) to work on /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:51:45.812+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data_remote.py for tasks to queue
[2022-09-23T20:51:45.813+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:51:45.813+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:51:57.030+0000] {processor.py:768} INFO - DAG(s) dict_keys(['loading_data_remote']) retrieved from /opt/airflow/dags/load_data_remote.py
[2022-09-23T20:52:00.579+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:52:00.578+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-09-23T20:52:00.917+0000] {logging_mixin.py:117} INFO - [2022-09-23T20:52:00.917+0000] {dag.py:3328} INFO - Setting next_dagrun for loading_data_remote to None, run_after=None
[2022-09-23T20:52:01.033+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data_remote.py took 16.580 seconds
