[2022-09-22T20:48:47.488+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: loading_data.create_tables manual__2022-09-22T20:48:44.675905+00:00 [queued]>
[2022-09-22T20:48:47.518+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: loading_data.create_tables manual__2022-09-22T20:48:44.675905+00:00 [queued]>
[2022-09-22T20:48:47.519+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-22T20:48:47.520+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-09-22T20:48:47.520+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-22T20:48:47.584+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): create_tables> on 2022-09-22 20:48:44.675905+00:00
[2022-09-22T20:48:47.592+0000] {standard_task_runner.py:54} INFO - Started process 16077 to run task
[2022-09-22T20:48:47.598+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'loading_data', 'create_tables', 'manual__2022-09-22T20:48:44.675905+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmphj4pkuy4']
[2022-09-22T20:48:47.599+0000] {standard_task_runner.py:83} INFO - Job 37: Subtask create_tables
[2022-09-22T20:48:47.600+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/load_data.py
[2022-09-22T20:48:50.034+0000] {task_command.py:384} INFO - Running <TaskInstance: loading_data.create_tables manual__2022-09-22T20:48:44.675905+00:00 [running]> on host c1ab2cb1bbac
[2022-09-22T20:48:50.302+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=loading_data
AIRFLOW_CTX_TASK_ID=create_tables
AIRFLOW_CTX_EXECUTION_DATE=2022-09-22T20:48:44.675905+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-22T20:48:44.675905+00:00
[2022-09-22T20:48:50.328+0000] {logging_mixin.py:117} INFO - [Errno 2] No such file or directory: 'CARS_schema.sql'
[2022-09-22T20:48:50.329+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-09-22T20:48:50.356+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=loading_data, task_id=create_tables, execution_date=20220922T204844, start_date=20220922T204847, end_date=20220922T204850
[2022-09-22T20:48:50.445+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-09-22T20:48:50.532+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
