[2022-09-22T21:28:00.788+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: loading_data.insert_data manual__2022-09-22T21:27:48.622232+00:00 [queued]>
[2022-09-22T21:28:00.834+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: loading_data.insert_data manual__2022-09-22T21:27:48.622232+00:00 [queued]>
[2022-09-22T21:28:00.835+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-22T21:28:00.835+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-09-22T21:28:00.836+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-22T21:28:00.935+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): insert_data> on 2022-09-22 21:27:48.622232+00:00
[2022-09-22T21:28:00.942+0000] {standard_task_runner.py:54} INFO - Started process 17558 to run task
[2022-09-22T21:28:00.951+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'loading_data', 'insert_data', 'manual__2022-09-22T21:27:48.622232+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmphiwb5pkg']
[2022-09-22T21:28:00.952+0000] {standard_task_runner.py:83} INFO - Job 56: Subtask insert_data
[2022-09-22T21:28:00.954+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/load_data.py
[2022-09-22T21:28:03.689+0000] {task_command.py:384} INFO - Running <TaskInstance: loading_data.insert_data manual__2022-09-22T21:27:48.622232+00:00 [running]> on host c1ab2cb1bbac
[2022-09-22T21:28:04.304+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=loading_data
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-22T21:27:48.622232+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-22T21:27:48.622232+00:00
[2022-09-22T21:28:04.310+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_data.py", line 39, in insert_to_table
    create_engine()
TypeError: create_engine() missing 1 required positional argument: 'url'
[2022-09-22T21:28:04.534+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=loading_data, task_id=insert_data, execution_date=20220922T212748, start_date=20220922T212800, end_date=20220922T212804
[2022-09-22T21:28:04.591+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 56 for task insert_data (create_engine() missing 1 required positional argument: 'url'; 17558)
[2022-09-22T21:28:04.632+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-22T21:28:04.681+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
