[2022-09-23T00:35:20.802+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: loading_data.load_table manual__2022-09-23T00:35:10.686680+00:00 [queued]>
[2022-09-23T00:35:20.828+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: loading_data.load_table manual__2022-09-23T00:35:10.686680+00:00 [queued]>
[2022-09-23T00:35:20.829+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-23T00:35:20.829+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-09-23T00:35:20.829+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-23T00:35:20.887+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): load_table> on 2022-09-23 00:35:10.686680+00:00
[2022-09-23T00:35:20.896+0000] {standard_task_runner.py:54} INFO - Started process 491 to run task
[2022-09-23T00:35:20.901+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'loading_data', 'load_table', 'manual__2022-09-23T00:35:10.686680+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmp0a2862db']
[2022-09-23T00:35:20.902+0000] {standard_task_runner.py:83} INFO - Job 118: Subtask load_table
[2022-09-23T00:35:20.906+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/load_data.py
[2022-09-23T00:35:22.138+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 118 for task load_table (Task load_table not found; 491)
[2022-09-23T00:35:22.200+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-23T00:35:22.320+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
